name: composite-action-ex
description: add you description here
runs: 
  using: composite
  steps:
    - name: idiotic-step-a
      run: echo "1"
      shell: bash

    - name: idiotic-step-b
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: idiotic-step-c
      run: python -c "print(2)"
      shell: bash