name: composite-action-with-io-ex
description: add you description here
inputs:
  init-number: 
    required: false  
    default: 10
outputs:
  final-number:
    value: ${{ steps.order66.output.number-output }}
runs: 
  using: composite
  steps:
    - name: python-install
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: get-final-number
      id: order66
      shell: bash
      run: |
        touch result.txt
        python -c "print(${{ inputs.length }}**2)" > result.txt
        echo "number-output=$(cat result.txt)" >> $GITHUB_OUTPUT