name: composite-action-with-io-ex
description: add you description here
inputs:
  init-number: 
    required: false  
    default: 10
outputs:
  final-number:
    value: ${{ steps.order66.output.number-output }}
runs: 
  using: composite
  steps:
    - name: python-install
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: get-final-number
      id: order66
      shell: bash
      run: |
        echo "number-output=$(python -c 'print(int(${{ inputs.init-number }})**2)')" >> $GITHUB_OUTPUT