[package]
name = "rust_euclidean_algo"
authors = ["Vinicius Pedroso <vpedroso@wiley.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
