name: twelth-workflow
on: workflow_dispatch
jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: fail-step
        id: fail-step
        run: cat ~/non_existent_folder/non_existent_file.txt
  
  conditional-job:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: error-message
        run: |
          echo "Something went wrong"
          echo ${{ github }}


      