name: fourteenth-workflow
on: workflow_dispatch
jobs:
  matrix-job:
    strategy:
      matrix:
        python-options: ["3.9","3.10","3.11"]
        os-options: ["ubuntu-latest","windows-latest"]
    runs-on: ${{ matrix.os-options }}
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4

      - name: python-setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-options }}

      - name: run-py-script
        run: python source/file_counter.py