name: sixteenth-workflow
on: workflow_dispatch

jobs:
  first:
    uses: ./.github/workflows/15th_wfl.yaml

  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: the-end
        run: echo "THE END"
    