name: nineteenth-workflow
on:
  workflow_call:
    inputs:
      fruit:
        required: true
        type: string
    outputs:
      taste-review:
        value: ${{ jobs.fruit-classifier.outputs.taste-output }}
jobs:
  fruit-classifier:
    runs-on: ubuntu-latest
    outputs:
      taste-output: ${{ steps.order66.outputs.taste-var }}
    steps:
      - name: step-output
        id: order66
        run: |
          echo "taste-var='${{ inputs.fruit }} is good'" >> $GITHUB_OUTPUT
