name: twentieth-workflow
on: 
  workflow_dispatch
jobs:
  client-job:
    uses: ./.github/workflows/nineteenth-workflow.yaml
    with:
      fruit: kiwi
  final-job:
    runs-on: ubuntu-latest
    needs: client-job
    run: echo "${{ needs.client-job.outputs.taste-review }}"