name: twentieth-fifth-workflow
on:
  workflow_dispatch
jobs:
  single-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch-checkout 
        uses: actions/checkout@v4

      - name: composite-action-with-io
        uses: ./.github/actions/composite_action_with_io_ex
        with:
          length: 12

      - name: display-output
        id: cowabunga
        run: echo "${{ steps.cowbunga.outputs.result }}"
