name: twenty-sixth-workflow
on:
  workflow_dispatch
jobs:
  single-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch-checkout
        uses: actions/checkout@v4
      
      - name: docker-action
        uses: ./github/actions/docker_action_ex
        with:
          length: 9

      - name: display-output
        id: cowabunga
        run: echo ${{ steps.cowabunga.list }}