name: seventh-workflow
on: 
  push:
    branches: 
      - "main"
jobs:
  create-output-job:
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.storing-file-content.outputs.test_result }}
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4
  
      - name: creating-file
        run: |
          mkdir test
          touch ./test/test.txt

      - name: writing-to-file
        run: echo "THIS IS A TEST" >> ./test/test.txt

      - name: storing-file-content
        id: storing-file-content
        run: echo "test_result=$(cat ./test/test.txt)" >> $GITHUB_OUTPUT
  
  display-output-job:
    runs-on: ubuntu:latest
    needs: create-output-job
    steps:
      - name: display-output
        run: echo "${{ needs.create-output-job.outputs.test_result }}"

    
