name: third-workflow
on: push
jobs:
  # JOB 1
  count-files:
    runs-on: ubuntu-latest
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4

      - name: python-setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: run-py-script
        run: python source/count_files_write_logs.py

  # JOB 2
  read-logs:
    needs: count-files #job which the current job depends on!
    runs-on: ubuntu-latest
    steps:
      - name: read-logs
        run: tail -n1 source/logs.txt